apiVersion: v1
kind: Service
metadata:
  name: bigdream
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "bigdream"
    port: 8080
  selector:
    app: bigdream
